### ISSUE TITLE
connection web-notification

### ISSUE THREAD

**Issue by bhavanakarwade** [credebl/studio#232]
## Description of feature/user story

 As a user, I want to receive notifications regarding the connection is established or not.

## Acceptance Criteria

- Given a user of a system or application that requires a connection with a holder
- When a user establishes a connection
- Then a user received notifications about whether the connection has been successfully established or if there was an issue preventing the connection.

## Task
- [x] Add connection notification in the notification service ( Backend)
- [x] Find out the best approach for sending messages from the platform to UI
- [ ] Create a subscription page to listen to all types of messages (Frontend)
- [ ] Design a custom UI for notification (Frontend)
- [ ] Create an API to get all notification list based on userId (Backend)
- [ ] Create an API to view specific notification (Backend)
- [ ] Create an API to update the view status (Backend)

**Comment by tipusinghaw** [comment]
As discussed, Implement this feature in the future
